services:
  myhistree:
    build:
      context: .
      dockerfile: Dockerfile
    image: myhistree-myhistree:latest
    container_name: myhistree
    restart: unless-stopped
    ports:
      - "3456:3456"
    volumes:
      - ./data:/app/data
    env_file: .env
    environment:
      - NODE_ENV=production
      - TZ=Europe/Berlin
      - PORT=3456
      - DB_PATH=/app/data/myhistoree.db
    networks:
      - myhistree

networks:
  myhistree:
    driver: bridge
